### PR TITLE
remove the spaces of the hash the user add

### LINKED ISSUE #47: Trim hash or domain
I think timming would improve the UX here:

Selection_041
Selection_040

Also maybe make errors red here - nearly did not see something went wrong with the neutral text between 2 green elements ;)

### PR DESCRIPTION
**Pull request by tropicar**
fix #47

### CODE REVIEW

File: build/server/src/utils/multiname.ts [hunk 1]
```diff
@@ -15,7 +15,8 @@ export const splitMultiname = (multiname: string): string[] =>
     .replace(/^\/+|\/+$/g, "")
     .split(separator)
     .filter(p => p)
-    .map(decodeURIComponent);
+    .map(decodeURIComponent)
+    .map(s => s.trim());
```
Comment (dapplion) [inline build/server/src/utils/multiname.ts:19]: You can do this in a single iteration

**Review by dapplion — APPROVED** [review]

**Comment by dapplion** [comment]
Tests are failing but seems unrelated. Could you investigate?

**Comment by tropicar** [comment]
The test problem is now fixed in the pr https://github.com/dappnode/DAppNodePackage-ipfs-pinner/pull/52
